name: pacman
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ghost.png
    - assets/images/ghost2.png
    - assets/images/ghost3.png
    - assets/images/pacman.png
    - assets/sounds/pacman_chomp.wav
    - assets/sounds/pacman_death.wav
    - assets/sounds/pacman_intermission.wav
    - assets/sounds/pacman_beginning.wav  
